import ageRange from "../src/assets/ageRange.png";
import femaleWorkers from "../src/assets/femaleWorkers.png";
import resign from "../src/assets/resign.png";
import university from "../src/assets/university.png";

const questions = [
  {
    question: "What is the capital of France?",
    options: ["Berlin", "Madrid", "Paris"],
    correct: "Paris",
    bgImage: ageRange,
    highlights: ["capital", "France"],
    answerText: "Females",
  },
  {
    question: "Who is the CEO of Techpoint?",
    options: ["Chidinma", "Yinka", "Muyiwa"],
    correct: "Muyiwa",
    bgImage: femaleWorkers,
    highlights: ["is", "CEO"],
    answerText: "Females",
  },
  {
    question: "Who is Techpoint Digest author?",
    options: ["Chimgozirim", "Victoria", "Oluwanifemi"],
    correct: "Victoria",
    bgImage: resign,
    highlights: ["author"],
    answerText: "Females",
  },
  {
    question: "What year was Techpoint founded?",
    options: ["2015", "2009", "2020"],
    correct: "2015",
    bgImage: university,
    highlights: ["year", "founded"],
    answerText: "Females",
  },
  {
    question: "What is the capital of Lagos?",
    options: ["Berlin", "Madrid", "Paris"],
    correct: "Paris",
    bgImage: ageRange,
    highlights: "capital",
    answerText: "Females",
  },
  {
    question: "Who is the CEO of PAtricia?",
    options: ["Chidinma", "Yinka", "Muyiwa"],
    correct: "Muyiwa",
    bgImage: femaleWorkers,
    highlights: ["is", "CEO"],
    answerText: "Females",
  },
  {
    question: "Who is Modern workplace author?",
    options: ["Chimgozirim", "Victoria", "Oluwanifemi"],
    correct: "Victoria",
    bgImage: resign,
    highlights: "author",
    answerText: "Females",
  },
  {
    question: "What year was Patricia founded?",
    options: ["2015", "2009", "2020"],
    correct: "2015",
    bgImage: university,
    highlights: ["year", "founded"],
    answerText: "Females",
  },

  {
    question: "What is the capital of Akwa-Ibom?",
    options: ["Berlin", "Madrid", "Paris"],
    correct: "Paris",
    bgImage: ageRange,
    highlights: "capital",
    answerText: "Females",
  },
  {
    question: "Who is the CEO of Altschool?",
    options: ["Chidinma", "Yinka", "Muyiwa"],
    correct: "Muyiwa",
    bgImage: femaleWorkers,
    highlights: ["is", "CEO"],
    answerText: "Females",
  },
  {
    question: "Who is Equity merchants author?",
    options: ["Chimgozirim", "Victoria", "Oluwanifemi"],
    correct: "Victoria",
    bgImage: resign,
    highlights: "author",
    answerText: "Females",
  },
  {
    question: "What year was The Front founded?",
    options: ["2015", "2009", "2020"],
    correct: "2015",
    bgImage: university,
    highlights: ["year", "founded"],
    answerText: "Females",
  },
  {
    question: "What is the capital of Ogun?",
    options: ["Berlin", "Madrid", "Paris"],
    correct: "Paris",
    bgImage: ageRange,
    highlights: "capital",
    answerText: "Females",
  },
  {
    question: "Who is the CEO of UBA?",
    options: ["Chidinma", "Yinka", "Muyiwa"],
    correct: "Muyiwa",
    bgImage: femaleWorkers,
    highlights: ["is", "CEO"],
    answerText: "Females",
  },
  {
    question: "Who is Americana's author?",
    options: ["Chimgozirim", "Victoria", "Oluwanifemi"],
    correct: "Victoria",
    bgImage: resign,
    highlights: "author",
    answerText: "Females",
  },
  {
    question: "What year was TalentQL founded?",
    options: ["2015", "2009", "2020"],
    correct: "2015",
    bgImage: university,
    highlights: ["year", "founded"],
    answerText: "Females",
  },
  {
    question: "What year was BBNaija founded?",
    options: ["2015", "2009", "2020"],
    correct: "2015",
    bgImage: university,
    highlights: ["year", "founded"],
    answerText: "Females",
  },
];

export default questions;
